# Generated by Django 4.1.3 on 2024-07-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classattend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='course',
            field=models.CharField(default='course', max_length=200),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='email',
            field=models.EmailField(default='email', max_length=254),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='firstName',
            field=models.CharField(default='firstName', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lastName',
            field=models.CharField(default='lastName', max_length=100),
        ),
    ]
